---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-pipeline
  namespace: seldon-model
  labels:
    app: seldon
spec:
  annotations:
    project_name: seldon-pipeline
    deployment_version: v0.0.1
    seldon.io/rest-read-timeout: '100000'
    seldon.io/rest-connection-timeout: '100000'
    seldon.io/grpc-read-timeout: '100000'
  name: seldon-pipeline
  oauth_key: oauth-key
  oauth_secret: oauth-secret
  predictors:
  - componentSpecs:
    - spec:
        containers:
        terminationGracePeriodSeconds: 20
        - name: sentiment
          image: mingboiz/seldon-sentiment:v0.0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
        - name: tagger
          image: mingboiz/seldon-tagger:v0.0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
        - name: summarizer
          image: mingboiz/seldon-summarizer:v0.0.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
    graph:
    name: pipeline
      name: sentiment
      endpoint:
        type: REST
      type: MODEL
      children:
      - name: tagger
        endpoint:
          type: REST
        type: MODEL
        children:
        - name: summarizer
          endpoint:
            type: REST
          type: MODEL
          children: []
    replicas: 1
    annotations:
      predictor_version: v1